version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      APP_ENV: development
      DATABASE_URL: sqlite+aiosqlite:///./app.db
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: npm run dev -- --host 0.0.0.0 --port 5173
    working_dir: /app
    environment:
      VITE_API_BASE_URL: http://127.0.0.1:8000/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
